/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 UnicornNew.glb 
Author: assetfactory (https://sketchfab.com/assetfactory)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-unicorn-pool-float-db2cf9d2a14448a58dfdd7fd653d8dac
Title: White unicorn pool float
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/UnicornNew.glb");
  const unicornRef = useRef(null);
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();

    unicornRef.current.rotation.y = elapsedTime / 8;
    unicornRef.current.position.x = elapsedTime / 50;
    // unicornRef.current.rotation.y = elapsedTime / 8;
  });

  return (
    <group ref={unicornRef}>
      <group
        {...props}
        dispose={null}
        rotation={[0, 1.2, 0.5]}
        scale={[0.3, 0.3, 0.3]}
        position={[0, 1.5, 0]}
      >
        <group scale={0.01}>
          <mesh
            geometry={nodes.Torus004_Material001_0.geometry}
            material={materials["Material.001"]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/UnicornNew.glb");
